spring:
  application:
    name: auth-service

  datasource:
    url: ${MY_ORDER_SERVICE_DB_HOST}
    username: ${MY_ORDER_SERVICE_DB_USERNAME}
    password: ${MY_ORDER_SERVICE_DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: liquibase/changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  expiration: 1480 # minutes

logging:
  level:
    org.springframework.security: DEBUG
